import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container + ' bg-pretzels '}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={
          styles.main +
          ' bg-opacity-30 backdrop-blur-md bg-slate-500 rounded-lg'
        }
      >
        <div className="flex flex-row">
          <img src="/images/cp_2.png" className="w-16 mr-6" />
          <h1 className={styles.title}>
            Welcome to <a href="https://pretzeldao.com">SugarPretzels!</a>
          </h1>
          <img src="/images/cp_1.png" className="w-16 ml-6" />
        </div>

        <p className={styles.description}>
          Get started by minting your{' '}
          <code className={styles.code}>pretzels</code>
        </p>

        <div className={styles.grid}>
          <a href="ttps://pretzeldao.com" className={styles.card}>
            <h2>PretzelDAO &rarr;</h2>
            <p>
              Find in-depth information about PretzelDAO, activities and
              Members.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
